version: 0.1.{build}-{branch}
os: Visual Studio 2015

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build_script:
  - nuget restore -Verbosity quiet SQL2016_BIDSHelper.sln
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m SQL2016_BIDSHelper.sln

after_test:
  - ps: Vsix-PushArtifacts

branches:
  only:
  - vs2015
